In [110]:
#Data Cleaning
import pandas as pd
import numpy as np

In [135]:
data = pd.read_csv(r'C:\Users\hp\Downloads\archive (1)\dubai_residential_data_2026.csv')

In [136]:
data.head()

,INSTANCE_DATE,PROCEDURE_EN,IS_FREE_HOLD_EN,AREA_EN,PROP_SB_TYPE_EN,TRANS_VALUE,ACTUAL_AREA,ROOMS_EN,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,PROJECT_EN,price_per_sqm,size_category,value_band
0,1/2/2026,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.0,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End
1,1/2/2026,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.0,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End
2,3/9/2026,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.0,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry
3,3/6/2026,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.0,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,NaN,14650.03,Compact,Entry
4,3/6/2026,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.0,66.50,1 B/R,Rashidiya Metro Station,City Centre Mirdif,NaN,NaN,7744.36,Mid-Size,Entry

In [137]:
data.describe()

        TRANS_VALUE   ACTUAL_AREA  price_per_sqm
count  1.808500e+04  18085.000000   1.808500e+04
mean   1.857787e+06     94.380744   1.864498e+04
std    2.756622e+06     77.235185   2.056915e+04
min    2.312380e+03      7.310000   3.310000e+01
25%    7.300000e+05     54.770000   1.139983e+04
50%    1.190000e+06     78.110000   1.579517e+04
75%    2.098512e+06    115.530000   2.259084e+04
max    1.000000e+08   4827.040000   2.207993e+06

In [139]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18085 entries, 0 to 18084
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   INSTANCE_DATE        18085 non-null  object
 1   PROCEDURE_EN         18085 non-null  object
 2   IS_FREE_HOLD_EN      18085 non-null  object
 3   AREA_EN              18085 non-null  object
 4   PROP_SB_TYPE_EN      18085 non-null  object
 5   TRANS_VALUE          18085 non-null  float64
 6   ACTUAL_AREA          18085 non-null  float64
 7   ROOMS_EN             17723 non-null  object
 8   NEAREST_METRO_EN     14513 non-null  object
 9   NEAREST_MALL_EN      14332 non-null  object
 10  NEAREST_LANDMARK_EN  16433 non-null  object
 11  PROJECT_EN           14018 non-null  object
 12  price_per_sqm        18085 non-null  float64
 13  size_category        18085 non-null  object
 14  value_band           18085 non-null  object
dtypes: float64(3), object(12)
memory usage: 2.1+ MB

In [140]:
data.dtypes

INSTANCE_DATE           object
PROCEDURE_EN            object
IS_FREE_HOLD_EN         object
AREA_EN                 object
PROP_SB_TYPE_EN         object
TRANS_VALUE            float64
ACTUAL_AREA            float64
ROOMS_EN                object
NEAREST_METRO_EN        object
NEAREST_MALL_EN         object
NEAREST_LANDMARK_EN     object
PROJECT_EN              object
price_per_sqm          float64
size_category           object
value_band              object
dtype: object

In [141]:
#changing data type
data['INSTANCE_DATE'] = pd.to_datetime(data['INSTANCE_DATE'])
print(data['INSTANCE_DATE'].dtypes)

datetime64[ns]

In [142]:
#change date format
data['INSTANCE_DATE'].dt.strftime('%Y-%m-%d')

0        2026-01-02
1        2026-01-02
2        2026-03-09
3        2026-03-06
4        2026-03-06
            ...
18080    2026-05-08
18081    2026-05-18
18082    2026-05-18
18083    2026-05-20
18084    2026-01-23
Name: INSTANCE_DATE, Length: 18085, dtype: object

In [143]:
#handles Null values

In [144]:
(data.isnull().sum()/len(data))*100

INSTANCE_DATE           0.000000
PROCEDURE_EN            0.000000
IS_FREE_HOLD_EN         0.000000
AREA_EN                 0.000000
PROP_SB_TYPE_EN         0.000000
TRANS_VALUE             0.000000
ACTUAL_AREA             0.000000
ROOMS_EN                2.001659
NEAREST_METRO_EN       19.751175
NEAREST_MALL_EN        20.752004
NEAREST_LANDMARK_EN     9.134642
PROJECT_EN             22.488250
price_per_sqm           0.000000
size_category           0.000000
value_band              0.000000
dtype: float64

In [145]:
data = data.dropna(subset=['ROOMS_EN'])

In [146]:
data['NEAREST_METRO_EN'] = data['NEAREST_METRO_EN'].fillna('UNKNOWN')

In [147]:
data['NEAREST_MALL_EN'] = data['NEAREST_MALL_EN'].fillna('UNKNOWN')

In [148]:
data['NEAREST_LANDMARK_EN'] = data['NEAREST_LANDMARK_EN'].fillna('UNKNOWN')

In [149]:
data['PROJECT_EN'] = data['PROJECT_EN'].fillna('UNKNOWN')

In [150]:
data.isnull().sum()

INSTANCE_DATE          0
PROCEDURE_EN           0
IS_FREE_HOLD_EN        0
AREA_EN                0
PROP_SB_TYPE_EN        0
TRANS_VALUE            0
ACTUAL_AREA            0
ROOMS_EN               0
NEAREST_METRO_EN       0
NEAREST_MALL_EN        0
NEAREST_LANDMARK_EN    0
PROJECT_EN             0
price_per_sqm          0
size_category          0
value_band             0
dtype: int64

In [151]:
data['Months'] = data['INSTANCE_DATE'].dt.month_name()

In [152]:
data

,INSTANCE_DATE,PROCEDURE_EN,IS_FREE_HOLD_EN,AREA_EN,PROP_SB_TYPE_EN,TRANS_VALUE,ACTUAL_AREA,ROOMS_EN,NEAREST_METRO_EN,NEAREST_MALL_EN,NEAREST_LANDMARK_EN,PROJECT_EN,price_per_sqm,size_category,value_band,Months
0,2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2600000.00,140.95,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,BAHWAN TOWER,18446.26,Premium,High-End,January
1,2026-01-02,Sale,Free Hold,BURJ KHALIFA,Flat,2731642.00,134.46,2 B/R,Business Bay Metro Station,Dubai Mall,Downtown Dubai,Imperial Avenue,20315.65,Premium,High-End,January
2,2026-03-09,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,620000.00,42.87,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,PANTHEON ELYSEE,14462.33,Compact,Entry,March
3,2026-03-06,Sale,Free Hold,JUMEIRAH VILLAGE CIRCLE,Flat,540000.00,36.86,Studio,Nakheel Metro Station,Marina Mall,Sports City Swimming Academy,UNKNOWN,14650.03,Compact,Entry,March
4,2026-03-06,Sale,Free Hold,INTERNATIONAL CITY PH 1,Flat,515000.00,66.50,1 B/R,Rashidiya Metro Station,City Centre Mirdif,UNKNOWN,UNKNOWN,7744.36,Mid-Size,Entry,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18080,2026-05-08,Delayed Development,Non Free Hold,DUBAI INVESTMENT PARK SECOND,Flat,652813.25,75.79,1 B/R,UNKNOWN,UNKNOWN,Expo 2020 Site,RITAJ,8613.45,Mid-Size,Mid-Market,May
18081,2026-05-18,Delayed Development,Non Free Hold,SILICON OASIS,Flat,653775.00,48.59,Studio,UNKNOWN,UNKNOWN,IMG World Adventures,UNIESTATE MILLENNIUM TOWER,13454.93,Mid-Size,Mid-Market,May
18082,2026-05-18,Delayed Development,Non Free Hold,SILICON OASIS,Flat,1150477.00,98.35,1 B/R,UNKNOWN,UNKNOWN,IMG World Adventures,UNIESTATE MILLENNIUM TOWER,11697.78,Spacious,Mid-Market,May
18083,2026-05-20,Delayed Development,Non Free Hold,SILICON OASIS,Flat,1156794.00,98.37,1 B/R,UNKNOWN,UNKNOWN,IMG World Adventures,UNIESTATE MILLENNIUM TOWER,11759.62,Spacious,Mid-Market,May
18084,2026-01-23,Delayed Development,Non Free Hold,DUBAI INVESTMENT PARK SECOND,Flat,638997.19,77.07,1 B/R,UNKNOWN,UNKNOWN,Expo 2020 Site,RITAJ,8291.13,Mid-Size,Entry,January